version: "3.9"

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: beato-bot
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO} # Defaults to INFO if not provided
      DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/your-webhook-url"
      MONGO_URI: "your_mongo_connection_string"
      REDDIT_CLIENT_ID: "your_reddit_client_id"
      REDDIT_CLIENT_SECRET: "your_reddit_client_secret"
      REDDIT_USER_AGENT: "your_app_user_agent"
      FASTAPI_URL: "your fastapi_url"
      SUBREDDIT_NAME: "patfinnerty"
    volumes:
      - ./logs:/app/logs  # Optional local logging
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: beato-server
    ports:
      - "8000:8000"
    environment:
      LLM_REPO_ID: "hugging-quants/Llama-3.2-1B-Instruct-Q4_K_M-GGUF"   # Default, can override
      LLM_FILENAME: "llama-3.2-1b-instruct-q4_k_m.gguf"                 # Default, can override
    restart: unless-stopped